### ISSUE TITLE
可读性问题

### ISSUE THREAD

**Issue by winlock** [wxflogic/logic_vsi#4]
感谢您的重译，但是您目前的MD版本下载下来是这样的：

我们就可以把上面那个串连起来的推断写成如下形式：
$$ \dfrac{q\qquad\quad}{\dfrac{q\lor p\qquad \neg q}{p}} $$

或者：

若 $$a$$ 是任一语句，逻辑学家通常将论断“$$a$$ 一定为真” 记作 $$\Box a$$，将论断“$$a$$ 可能为真”记作 $$\Diamond a$$。

（用 Typora 和 Mark text 阅读都是如此。）
这实在是没法阅读啊。在线版本是可读的，但复制下来保存又有问题。
请问能不能给一个WORD或者PDF版本下载呢？

**Comment by wxflogic** [comment]
已添加由Typora导出的pdf文件。
