### ISSUE TITLE
第14章：停！发生什么了？

### ISSUE THREAD

**Issue by zhdm123** [wxflogic/logic_vsi#5]
一直在生啃英文版，对照阅读你翻译的中文版，收获良多。
发现你翻译的中文版修改了我在美亚上购买的英文版的一些错误，甚是惊喜。

关于14章的翻译中的一个细节，我有个疑问。

https://wxflogic.gitbook.io/logic/chapter14
![image](https://user-images.githubusercontent.com/25632385/98502033-f029c580-228b-11eb-87e9-4e25cc204a38.png)

关于这里面翻译的“最左列”，我联系上下文发现，这里应该说的是“对角线”。
因为我理解对于这里的论证过程，作者想要描述的是：
针对每一个x，T(x)和Px(x)的输出一定是不一样的，所以，T(x)一定不在这条对角线上，但是所有的程序都应该在这个对角线上有一个位置。
这样就出现了矛盾。

不知道我理解的是否有误，并且第一次使用github，关于用法和习俗也不太了解。
有冒犯之处和理解偏差之处，欢迎批评指正，多多交流。

**Comment by wxflogic** [comment]
谢谢你的问题！

我觉得翻译没有问题。对角线上并不是程序，而是程序Px输入x后的运行结果，而T的输入是所有程序（由最左列的数字编码）。

zhdm123 <notifications@github.com> 于2020年11月9日周一 下午1:17写道：

**Comment by zhdm123** [comment]
看完回复，我觉得应该是我的理解问题。
我又重新去读了这章，还是主要卡到这个位置。我对于“T为什么不在程序的列表里”的推论过程，没有能够按照作者的意思理解或者是我理解不了。
我的理解是，在表中，所有输入 传入T，得到的结果是表中的一横，一定在T（t）处相交。但是因为 T的定义决定了 T（x）和 X（x） 《x从0到无穷大》不可能相交。
我还是只能按照这章紧前面介绍的图灵的证明方式来理解这个表的矛盾。感觉不太对，关于这里的理解，有没什么建议？

**Comment by zhdm123** [comment]
找了一个油管视频，视频中介绍了一下 对角线 ，才算是有点儿理清楚了。自己想不明白。后面继续想。
